name: Actualizador Automático de Lista

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecutará automáticamente cada 6 horas
  workflow_dispatch:      # Permite que tú lo actives manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Estos permisos son vitales para que no salga la X roja
    permissions:
      contents: write

    steps:
      - name: 1. Descargar mi repositorio
        uses: actions/checkout@v3

      - name: 2. Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Instalar librerías necesarias
        run: pip install requests

      - name: 4. Ejecutar el script actualizador
        run: python update_list.py

      - name: 5. Guardar y subir cambios a mi GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "LISTA VERSASERa.m3u"
          git commit -m "Enlaces actualizados automáticamente" || exit 0
          git push
